### ISSUE TITLE
GP-GAN: error while blending with cpu.

### ISSUE THREAD

**Issue by CmdrMahesh** [msinghal34/Image-Blending-using-GP-GANs#1]
Hi,
I ran the solution with this command 

`python3.6 blend.py -src test/src.png -dest dest.png -mask test/mask.png -model network_weights`

and got this pytorch error:

```
raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
i know its due to cuda no available at my system but have installed cpu version of pytorch and also i saw that in your codes you took care of it with `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")` which is good but still i'm facing this issue, so any help will be greatfull.
Thanks.

**Comment by msinghal34** [comment]
I think changing Line 39 in blend.py to 
`net.load_state_dict(torch.load(args.model, map_location=device))` 
will cause the error to go away. 
But this code was not meant to be run on a CPU and it might even take more than half an hour or so on CPU.

**Comment by CmdrMahesh** [comment]
thanks for the reply, and yes I added this solution a day ago after googling it a lot. either way, thanks buddy for this repo.

**Comment by CmdrMahesh** [comment]
When I ran this on CPU I waited for more than 3 hours and the consol got stuck by showing the following lines :
```
1024
512
256
128
64

```
any hint if I am doing something wrong.
thanks.

**Comment by msinghal34** [comment]
When I ran it on my 8 core CPU & 8 GB RAM, it took ~50 minutes. I don't think you are doing anything wrong, it is just that it needs a lot of time to run on a CPU. Better try to run it on Google colab.

**Comment by CmdrMahesh** [comment]
thank you for the advice.
